apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wyze-tickets-secrets
  namespace: wyze
spec:
  encryptedData:
    REDIS_PORT: AgA7Z0Z7AWC/R7lHVqHid/Ssb7OvUuZjjPpS74B/01jBtCHn0BSMIqHFl4XKgDcYium2qwuvJsBpv1+kaKYEyJGnjGkmmjF8O5EmoC+QUFPbEA8yR7Axd9xWFBAskDCTAToIGwPcaHIg0SV8I9pHwqYaNvOsFm7hC++91kIt3YmK4K2sK2Y3eXV9HbYlTaJ9QQyRq1xVNzk62Vicw/k2/6gVL4Q3nXDwXm2/Rh6My5Mx1aPFwqh9V3W1EevBWQT2xJMkoCLhdF71CzzfXxHmHnCLhM8Nx9Kqgmrd+Bgr6awQjyDer606ieJY6nebfzUXh+Vn9kNkac/RRGQchw20Cdd3ZSYkcelAzmuorU9b08nj3yFE5u6dIx8RjpmqSzYhTvonT+BNvm6tV+AX/FOptFOmDmDxpBAce2DCxDLan3phx8BUFm68Ksa+K76N6MDdWiYg0qDO/FLtN7E7+Qm6dXR/VPMCiQ8p5ue2G7fcCKapRqYvuPGQy7FHcAK88DGQxZubU5aYwuLk189yQQAcS4sZusACOHXfTUanx3x+B7TebT9fDgZNa0j+oRRi9bJ+2Js8gHs43sl2juMtxglVqovzU3XOEOFMw6pIZPp/yTwS3679vP8TCl2GHLBn3Qt8P1kmzD5zFgIcfsaSilJg3Z04rtrz6vEDRkZRbQycMw0vqp5r7W+o1rgKVnwiXtYgG1Qb6iZn
    REDIS_SERVICE: AgBQUowrWEqs4y+WFlHq72AW5W9+wGnXQUXyl/n4FFMhuRz3jEqyjqixGBX0eppf72wi/KqVbl1Wz21p9uvrqglkmBLEiEf9cEr0iWCDN0YJpH2Ljn8AF11kiXVoRhUwVpY9vEXtl7QQi4OGuGybV2nLOTD14RR7PovPBaIpAJbt6I2uLGdAYj0niNSaZykVwGkpY+c2yCL+f7CJN5eKVsd39zvnY+aTV8dvWcZ33RyNMyH3DvEItS2z/PDh3R0VMdPTX4NBpnkPP/ecAbejBFM9BDZqZPL9cgxCZ9C3y5DC2P06DYFZ+qwQQ3Qv+ebj+6JCKAjyW2MncfodxqzgCrSTJUXtDFwIFpm2qIF68mlkzTuvqDbVPJ0FbFrrko7bmIY9msmZafF3uoZXEIcF8OSDZJ8aywoYo591mS3nJqPiTW0+bwvsgBVH0s/0rf+KcnXsaAYS9GLr51BYfjB23afl2DvJZzotG+CltZlIFrDzVKDT8A+MBkLH1iPxUaJrLbIPki34nXbexKNE6FIdKojoHhGLE1iYFI4rQdKDx3xZW43lEAJQ7qLtahGIZ3Igz98dtGjHWQ1dk6Ujkb90Hk5BuZ2ID5mjKy/jnc9f6lO+/SujHwuANi7IEoPq7i88dAAT1sxcfoV6XTli13eUa6Me5QMeHV6AYmDUypPa6J196JzdGyI75XByJjoA4UuSVz7RcKtF1Whk1LKlIciqhtXjgmk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: wyze-tickets-secrets
      namespace: wyze
    type: Opaque

