module "postgresql_rds" {
  source = "github.com/azavea/terraform-aws-postgresql-rds"
  vpc_id = var.vpc_id
  allocated_storage = "32"
  engine_version = "12.10"
  instance_type = "db.t2.micro"
  storage_type = "gp2"
  database_identifier = "wyze"
  database_name = "wyze"
  database_username = "wyze"
  database_password = "wyzepostgres"
  database_port = "5432"
  backup_retention_period = "30"
  backup_window = "04:00-04:30"
  maintenance_window = "sun:04:30-sun:05:30"
  auto_minor_version_upgrade = false
  multi_availability_zone = false
  storage_encrypted = false
  subnet_group = var.database_subnet_group_name
  monitoring_interval = "60"
  deletion_protection = false
  cloudwatch_logs_exports = ["postgresql"]
  parameter_group = "default.postgres12"
  alarm_cpu_threshold = "75"
  alarm_disk_queue_threshold = "10"
  alarm_free_disk_threshold = "5000000000"
  alarm_free_memory_threshold = "128000000"
  alarm_actions = [var.sns_arn]
  ok_actions = [var.sns_arn]
  insufficient_data_actions = [var.sns_arn]

  project = "Wyze"
  environment = "Production"
}

# output "id" {
#   value       = module.postgresql_rds.postgresql.id
#   description = "The database instance ID"
# }

# output "database_security_group_id" {
#   value       = module.postgresql_rds.postgresql.id
#   description = "Security group ID of the database"
# }

# output "hosted_zone_id" {
#   value       = aws_db_instance.postgresql.hosted_zone_id
#   description = "The zone ID for the autogenerated DNS name given in endpoint"
# }

# output "hostname" {
#   value       = aws_db_instance.postgresql.address
#   description = "Public DNS name of database instance"
# }

# output "port" {
#   value       = aws_db_instance.postgresql.port
#   description = "Port of database instance"
# }

# output "endpoint" {
#   value       = aws_db_instance.postgresql.endpoint
#   description = "Public DNS name and port separated by a colon"
# }
