apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wyze
  name: wyze-events-cron
  labels:
    app: wyze-events-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wyze-events-cron
  template:
    metadata:
      labels:
        app: wyze-events-cron
    spec:
      containers:
        - name: wyze-events-cron
          image: ryanpkennedy/wyze-events-cron:sha-3e0315e
          command: ['bash', '-c', 'sleep 30; npm run prod-cron']
          env:
            - name: runOnInit
              value: 'false'
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: DATABASE_HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: DATABASE_NAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: DATABASE_PORT
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: DATABASE_USERNAME
            - name: SEATGEEK_KEY
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: SEATGEEK_KEY
            - name: STUBHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: STUBHUB_KEY
            - name: TICKETMASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: wyze-events-cron-secrets
                  key: TICKETMASTER_KEY
      imagePullSecrets:
        - name: dockerhub-secrets
